name: Deploy to Cloud Run (master)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Google Cloud 認証を行う
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Cloud SDK のセットアップ（入力は service_account_key ではなく project_id などのみにする）
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: tough-descent-411304
          # 必要に応じてバージョンやインストールコンポーネントも指定可能
          version: 'latest'

      # Cloud Run へのデプロイ
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy anshiba-report-notify-discord-bot \
            --image us-central1-docker.pkg.dev/tough-descent-411304/discord-bot-rehistry/anshiba-report-notify-discord-bot:latest \
            --region us-central1 \
            --platform managed \
            --quiet
